language: php
sudo: required
dist: trusty
group: deprecated-2017Q4

cache:
  directories:
    - $HOME/.composer/cache
    - /home/travis/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  # plugin code
  global:
    PLUGIN_CODE=Point
  matrix:
    # ec-cube 3.0.16
    - ECCUBE_VERSION=dev/3.0.16 DB=mysql USER=root DBNAME=myapp_test DBPASS=' ' DBUSER=root
    - ECCUBE_VERSION=dev/3.0.16 DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres

install:
  - gem install mime-types -v 2.99.1
  - gem install mailcatcher

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

before_script:
  # archive plugin
  - tar cvzf ${HOME}/${PLUGIN_CODE}.tar.gz ./*
  # clone ec-cube
  - git clone https://github.com/EC-CUBE/ec-cube.git
  - cd ec-cube
  # checkout version
  - sh -c "if [ ! '${ECCUBE_VERSION}' = 'master' ]; then  git checkout ${ECCUBE_VERSION}; fi"
  # update composer
  - composer selfupdate
  - composer global require hirak/prestissimo
  - composer install --dev --no-interaction -o
  # install ec-cube
  - sh eccube_install.sh ${DB} none
  # install plugin
  - php app/console plugin:develop install --path=${HOME}/${PLUGIN_CODE}.tar.gz
  # enable plugin
  - php app/console plugin:develop enable --code=${PLUGIN_CODE}
  - mailcatcher

script:
  # exec phpunit on ec-cube
  - phpunit app/Plugin/${PLUGIN_CODE}/Tests

after_script:
  # disable plugin
  - php app/console plugin:develop disable --code=${PLUGIN_CODE}
  # uninstall plugin
  - php app/console plugin:develop uninstall --code=${PLUGIN_CODE}
  # re install plugin
  - php app/console plugin:develop install --code=${PLUGIN_CODE}
  # re enable plugin
  - php app/console plugin:develop enable --code=${PLUGIN_CODE}
